basedir: /

# html lang
language: "en"

# main menu navigation
menu:
  Welcome: welcome
  Speakers: speakers
  # Schedule: schedule
  # Workshops: workshops
  Sponsor: sponsor

# welcome submenu
welcome_submenu:
  COC: coc
  Scholarships: scholarships

# footer menu navigation
# footer_menu:
#   Top: top
#   Tickets: schedule
#   Sponsor: sponsor
#   Scholarships: scholarships
#   Talks: talks
#   Newsletter: newsletter

# stylesheets loaded in the <head>
stylesheets:
- /assets/css/grusp.css

# favicon
favicon: /assets/ico/favicon.ico

# scripts loaded in the end of the body / commented out to prevent errors in compiling layout.pug
scripts:
- /assets/js/menu.js

open_graph:
  type: website
  title: page.title
  name: config.title
  url: config.url
  description: config.description
  locale: config.language
  image: 'themes/grusp/source/assets/img/grusp-logo-full.svg'
